name: publish-to-github-pages
on:
  push:
    branches:
      - master

permissions:
  contents: write
  # pages: write
  # id-token: write

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js - Install dependencies
  #       uses: ./.github/workflows/setup-node

  #     - name: Setup Pages
  #       uses: actions/configure-pages@v4
  #       with:
  #         static_site_generator: next

  #     - name: Build with Next.js
  #       run: |
  #         npm run build &&
  #         touch out/.nojekyll

  deploy:
    # environment:
    #   name: github-pages
    #   url: https://chaoyihu.github.io/

    runs-on: ubuntu-latest
    # needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: master